### ISSUE TITLE
Package to create a generic shiny interface on top of a parametrised rmarkdown report

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/pitcher#3]
# Automated Shiny Interface Generation from an Rmarkdown Template

## Description

This package would automatically generate the shiny app code based on a parametrized rmarkdown report to allow users to interactively select parameters.

This will require a standard way to define possible types and values in the rmarkdown parameters. From this, the appropriate shiny widget could be inferred. For example

- a numeric value between 0 and 1 should be a `sliderInput()`
- a factor should be a `radioButtons()`
- etc.

## Target audience

* typical end-users:

  - end-users of report packages, such as https://github.com/epiverse-trace/data_pipelines, but who don't feel confident enough to change the `params` values in the rmarkdown document
  - developers of report packages who want to easily provide a graphical interface for their package

* potential contributors: ??

* key collaborators: ??

## Interoperability

* inputs: rmarkdown report with parameters

* outputs: a shiny interface

* imports:
  - https://github.com/epiverse-trace/data_pipelines

* used by:
  - https://github.com/epiverse-trace/data_pipelines

* related projects:
  - ??

## Useful resources

- ["Code generation in R packages", by Maëlle Salmon](https://blog.r-hub.io/2020/02/10/code-generation/)

**Comment by Bisaloo** [comment]
Found this related project because I wanted to use the same name: https://github.com/sachsmc/polish :sweat_smile:

**Comment by Bisaloo** [comment]
Defaults, choices, min/max, etc. can be specified, as documented in https://bookdown.org/yihui/rmarkdown/params-knit.html#the-interactive-user-interface:

```yaml
---
title: My Document
output: html_document
params:
  year:
    label: "Year"
    value: 2017
    input: slider
    min: 2010
    max: 2018
    step: 1
    sep: ""
  region:
    label: "Region:"
    value: Europe
    input: select
    choices: [North America, Europe, Asia, Africa]
  printcode:
    label: "Display Code:"
    value: TRUE
  data:
    label: "Input dataset:"
    value: results.csv
    input: file
---
```
